it('Daftar worker', () =>{
    cy.visit('http://localhost:8000/login')
    cy.get('#email').type('user')
    cy.get('#password').type('123')
    cy.get('.btn-primary').click()
    cy.visit('http://localhost:8000/list-worker')
    cy.contains('Ingin jadi pekerja kami?').click()
    cy.contains('Kirim').click()
    cy.get('[class="select2-selection select2-selection--multiple"]').type('Java').type('{enter}')
    cy.get('[name="phone"]').type('081217660423')
    cy.get('[name="bank_account"]').type('12345678')
    cy.get('[name="address"]').type('Mojokerto')
    cy.get('[name="about"]').type('Mahasiswa')
    cy.get('[id="image"]').attachFile//('../fixtures/gambar1.png')
    cy.get('[id="ktp"]').attachFile('../fixtures/gambar1.png')
    cy.get('[id="cv"]').attachFile('../fixtures/gambar1.png')
    cy.get('button').contains('Submit').click()
})