it('Upload Portofolio', () =>{
    cy.visit('http://localhost:8000/login')
    cy.get('#email').type('worker')
    cy.get('#password').type('123')
    cy.get('.btn-primary').click()
    cy.visit('http://localhost:8000/profile-worker')
    cy.get('[id="home-tab"]').click()
    cy.contains('Upload portofoliomu').click()
    cy.get('#title').type('Portofolio')
    cy.get('#link').type('https://instagram.com/zhfframaf')
    cy.get('[type="file"]').attachFile('../fixtures/gambar1.png')
    cy.get('textarea').typeCkeditor("Testing PPL")
    cy.contains('Tambah Portofolio').click()
})