it('Profile Worker', () =>{
    cy.visit('http://localhost:8000/login')
    cy.get('#email').type('worker')
    cy.get('#password').type('123')
    cy.get('.btn-primary').click()
    cy.visit('http://localhost:8000/profile-worker')
    cy.get('[id="home-tab"]').click()
    cy.get('[id="profile-tab"]').click()
    cy.get('[id="contact-tab"]').click()
    cy.get('[id="income-tab"]').click()
})